# Generated by Django 4.0.4 on 2022-05-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Doc', 'Documentation'), ('Imp', 'Improvement')], default='Bug', max_length=100),
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('ToDo', 'ToDo'), ('Proc', 'Processing'), ('Done', 'Done')], default='ToDo', max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
