# Generated by Django 4.0.4 on 2022-05-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_category_issue_status_alter_issue_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Documentation', 'Documentation'), ('Improvement', 'Improvement')], default='Bug', max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Todo', 'Todo'), ('Processing', 'Processing'), ('Done', 'Done')], default='Todo', max_length=50),
        ),
    ]
